# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

inhibit_all_warnings!

target 'KNBKit' do
    pod 'YTKNetwork'
    pod 'Mantle'
    pod 'MagicalRecord'
    pod 'libextobjc'
    pod 'Masonry'
    pod 'SDWebImage'
    pod 'LLSimpleCamera'
    pod 'LCProgressHUD'
    pod 'MJRefresh'
end

target 'KNBKitTests' do
    pod 'Expecta'
end
