# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

inhibit_all_warnings!

target 'KNBKit' do
    pod 'YTKNetwork'
    pod 'Mantle'
    pod 'MagicalRecord'
    pod 'libextobjc'
    pod 'Masonry'
    pod 'SDWebImage'
    pod 'LLSimpleCamera', '~> 4.2.0'
    pod 'MJRefresh'
    pod 'LCProgressHUD'
    pod 'NJKWebViewProgress'
end
